services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "90:90"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - channel-metadata-store
    networks:
      - hazelcast-network

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    user: root
    links:
      - alertmanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For service discovery
      - ./prometheus:/etc/prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway' 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - hazelcast-network
  
  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: always
  
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    environment:
      #      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      #      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - './grafana/datasources:/etc/grafana/provisioning/datasources'
      - './grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yml'
      - './grafana/dashboard-backup/:/var/lib/grafana/dashboards'
    networks:
      - hazelcast-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'channel_metadata_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'none'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - hazelcast-network
      
  hazelcast:
    image: hazelcast/hazelcast:5.0.3
    volumes:
      - ./hazelcast/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
      - ./hazelcast/logs:/opt/hazelcast/logs
    command: hz start -c /opt/hazelcast/config/hazelcast.xml
    environment:
      - hazelcast.config=/opt/hazelcast/config/hazelcast.xml
      - hazelcast.diagnostics.directory=/opt/hazelcast/logs
    ports:
      - "5701-5704:5701"
    networks:
      - hazelcast-network
    deploy:
      replicas: 4  # Number of Hazelcast nodes

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - hazelcast-network

  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-1
    container_name: kafka-1
    expose:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9093,OUTSIDE://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "retry-db-write-from-cache:3:3"
    networks:
      - hazelcast-network

  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-2
    container_name: kafka-2
    expose:
      - "9095"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9095,OUTSIDE://kafka-2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hazelcast-network

  kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-3
    container_name: kafka-3
    expose:
      - "9097"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9097,OUTSIDE://kafka-3:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9097,OUTSIDE://0.0.0.0:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hazelcast-network

  channel-metadata-store:
    build: channel-metadata-store
    ports:
      - "8080"
    depends_on:
      - db
      - hazelcast
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/channel_metadata_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HAZELCAST_URL=hazelcast:5701
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
    networks:
      - hazelcast-network 
    labels:
      prometheus-scrape: "true"
    deploy:
      replicas: 4
    restart: always

  cache-retry:
    build: cache-retry
    ports:
      - "8090"
    depends_on:
      - channel-metadata-store
      - kafka-1
      - kafka-2
      - kafka-3
      - cache-retry-db
    networks:
      - hazelcast-network
    labels:
      prometheus-scrape: "true"
    deploy:
      replicas: 4
    restart: always

  cache-retry-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: cache-retry-db
    restart: always
    environment:
      MYSQL_DATABASE: 'cache_retry_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'none'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - ./init-cache-retry:/docker-entrypoint-initdb.d
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
    driver: bridge
