services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'channel_metadata_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'none'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - hazelcast-network
      
  hazelcast:
    image: hazelcast/hazelcast:5.0.3
    volumes:
      - ./hazelcast/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
      - ./hazelcast/logs:/opt/hazelcast/logs
    command: hz start -c /opt/hazelcast/config/hazelcast.xml
    environment:
      - hazelcast.config=/opt/hazelcast/config/hazelcast.xml
      - hazelcast.diagnostics.directory=/opt/hazelcast/logs
    ports:
      - "5701-5704:5701"
    networks:
      - hazelcast-network
    deploy:
      replicas: 4  # Number of Hazelcast nodes

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - hazelcast-network

  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-1
    container_name: kafka-1
    expose:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9093,OUTSIDE://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "retry-db-write-from-cache:3:3"
    networks:
      - hazelcast-network

  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-2
    container_name: kafka-2
    expose:
      - "9095"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9095,OUTSIDE://kafka-2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hazelcast-network

  kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-3
    container_name: kafka-3
    expose:
      - "9097"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9097,OUTSIDE://kafka-3:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9097,OUTSIDE://0.0.0.0:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hazelcast-network

  channel-metadata-store:
    build: channel-metadata-store
    ports:
      - 8080:8080
    depends_on:
      - db
      - hazelcast
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/channel_metadata_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HAZELCAST_URL=hazelcast:5701
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
    networks:
      - hazelcast-network 
    restart: always

networks:
  localprom:
    driver: bridge
  hazelcast-network:
    driver: bridge
