{
 "title": "Channel Metadata Store overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheusInstance", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Channel-metadata-store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current peak TPS 5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{status=\"200\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Failures 15m",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open|half-open\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Errors 15m",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{status!=\"200\"}[15m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_cache_hits_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(custom_cache_misses_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts?",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{container_name=~\"/distributed-systems-channel-metadata-store-.*\"}[10m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"docker-spring-boot-apps\", container_name=~\".*channel.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{container_name=~\"/distributed-systems-channel-metadata-store-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CMS application responses",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(http_server_requests_active_seconds_active_count) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic across replicas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_active_seconds_bucket{container_name=~\".*channel.*\"}[2m])) by (container_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "DB Read/Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(db_write_total{container_name=~\"/distributed-systems-channel-metadata-store-.*\"}) / 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum(db_read_total{container_name=~\"/distributed-systems-channel-metadata-store-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Requests",
   "type": "timeseries",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (kind) (resilience4j_circuitbreaker_calls_seconds_count{name=\"kafkaService\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"} / (1024 * 1024 * 1024)) / \nsum(jvm_memory_committed_bytes{area=\"heap\"} / (1024 * 1024 * 1024)) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{container_name=~\"/distributed-systems-channel-metadata-store-.*\"} * 100) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Status",
   "type": "timeseries",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|half_open|closed\"}) by (state)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache-retry-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current peak TPS 5m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{status=\"200\", container_name=~\"/distributed-systems-cache-retry-.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Failures 15m",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open|half-open\", container_name=~\"/distributed-systems-cache-retry-.*\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Errors 15m",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{status!=\"200\", container_name=~\"/distributed-systems-cache-retry-.*\"}[15m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts 24h",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{container_name=~\"/distributed-systems-cache-retry-.*\"}[10m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"docker-spring-boot-apps\", container_name=~\"/distributed-systems-cache-retry-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "see alto",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{container_name=~\"/distributed-systems-cache-retry-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CMS application responses",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(http_server_requests_active_seconds_active_count{container_name=~\"/distributed-systems-cache-retry-.*\"}) by (uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic across replicas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_active_seconds_bucket{container_name=~\"/distributed-systems-cache-retry-.*\"}[2m])) by (container_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", container_name=~\"/distributed-systems-cache-retry-.*\"} / (1024 * 1024 * 1024)) / \nsum(jvm_memory_committed_bytes{area=\"heap\", container_name=~\"/distributed-systems-cache-retry-.*\"} / (1024 * 1024 * 1024)) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{container_name=~\"/distributed-systems-cache-retry-.*\"} * 100) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Status",
   "type": "timeseries",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|half_open|closed\"}) by (state)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Requests",
   "type": "timeseries",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_fetch_rate{container_name=~\"/distributed-systems-cache-retry-.*\"}) by (container_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "barchart",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag_max{container_name=~\"/distributed-systems-cache-retry-.*\"}) by (container_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "barchart",
   "description": "Top line (hits\nBottom line (misses)",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_consumed_total{container_name=~\"/distributed-systems-cache-retry-.*\"}) by (container_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Read/Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
   "targets": [
    {
     "expr": "sum(db_write_total{container_name=~\"/distributed-systems-cache-retry-.*\"}) / 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum(db_read_total{container_name=~\"/distributed-systems-cache-retry-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}