global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /private/metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'service-metrics'
    scrape_interval: 10s
    metrics_path: /private/prometheus
    static_configs:
      - targets:
        - 'nginx:80'
