global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'service-metrics'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'nginx:80'
  - job_name: 'docker-spring-boot-apps'
    metrics_path: '/private/prometheus'  # Path where Spring Boot exposes its Prometheus metrics
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_docker_container_id]
        target_label: container_id  # Attach the container ID to metrics
      - source_labels: [__meta_docker_container_name]
        target_label: container_name  # Attach the container name to metrics
      - source_labels: [__meta_docker_container_network_mode]
        action: drop
        regex: host  # Drop containers using the host network mode